:sparkles: use build-one script instead of aur-install

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -75,29 +75,29 @@ jobs:
       - name: Build AUR package
         # 调用脚本，只传递一个包
         run: |
-          # bash scripts/build-one.sh ${{ inputs.package }}
+          bash scripts/build-one.sh ${{ inputs.package }}
           # 来自 docker image
-          aur-install ${{ inputs.package }}
+          # aur-install ${{ inputs.package }}
 
-      - name: Gather Build Results
-        run: |
-          # /var/cache/foreign-pkg 是 aur-install 放置构建的包的地方
-          find /var/cache/foreign-pkg -maxdepth 1 -name "*.pkg.tar.zst*" -exec mv {} "./" \;
+      # - name: Gather Build Results
+      #   run: |
+      #     # /var/cache/foreign-pkg 是 aur-install 放置构建的包的地方
+      #     find /var/cache/foreign-pkg -maxdepth 1 -name "*.pkg.tar.zst*" -exec mv {} "./" \;
 
-          # 检查是否真的有包被移动了过来
-          # `ls` 的结果通过 `wc -l` 计数，如果不为 0，说明成功了
-          if [ $(ls -1 ${REPO}*.pkg.tar.zst 2>/dev/null | wc -l) -eq 0 ]; then
-              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-              echo "!!! Critical Error: Build for '$REPO' did not produce any package files."
-              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-              exit 1
-          fi
+      #     # 检查是否真的有包被移动了过来
+      #     # `ls` 的结果通过 `wc -l` 计数，如果不为 0，说明成功了
+      #     if [ $(ls -1 ${REPO}*.pkg.tar.zst 2>/dev/null | wc -l) -eq 0 ]; then
+      #         echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+      #         echo "!!! Critical Error: Build for '$REPO' did not produce any package files."
+      #         echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+      #         exit 1
+      #     fi
 
-          echo "================================================="
-          echo "All packages built successfully!"
-          echo "Final packages in current directory:"
-          ls -l *.pkg.tar.zst*
-          echo "================================================="
+      #     echo "================================================="
+      #     echo "All packages built successfully!"
+      #     echo "Final packages in current directory:"
+      #     ls -l *.pkg.tar.zst*
+      #     echo "================================================="
 
       - name: Rename files with illegal characters
         run: |
